name: Generate lookup data from scripts

on:
  schedule:
    - cron: '0 2 * * *' # lets run 2am utc daily
  workflow_dispatch: # Allows you to run this manually for testing

permissions:
  contents: write # to put the csv into repo

jobs:
  icloud-proxy-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run script
        run: |
          python sources/icloud-proxy/icloud-proxy.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/icloud-proxy/
          git commit -m "Automated iCloud Proxy Data update: $(date)" || echo "No iCloud Proxy changes to commit"
          git push

  msft-office-data:
    needs: icloud-proxy-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run script
        run: |
          python sources/msft-office/msftoffice-ips.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/msft-office/
          git commit -m "Automated Microsoft Office IP Data update: $(date)" || echo "No Microsoft Office changes to commit"
          git push

  azure-cloud-data:
    needs: msft-office-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run script
        run: |
          python sources/msft-azurecloud/azure_ips.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/msft-azurecloud/
          git commit -m "Automated Azure Cloud IP Data update: $(date)" || echo "No Azure Cloud changes to commit"
          git push

  threatfox-ioc-data:
    needs: azure-cloud-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run script
        run: |
          python sources/threatfox-iocs/threatfox-ioc.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/threatfox-iocs/
          git commit -m "Automated ThreatFox IOC Data update: $(date)" || echo "No ThreatFox changes to commit"
          git push
