name: Generate lookup data from scripts

on:
  schedule:
    - cron: '0 2 * * *' # lets run 2am utc daily
  workflow_dispatch: # Allows you to run this manually for testing

permissions:
  contents: write # to put the csv into repo

jobs:
  data-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Pull iCloud Data
        run: |
          python sources/icloud-proxy/icloud-proxy.py

      - name: Pull O365 Data
        run: |
          python sources/msft-office/msftoffice-ips.py
          
      - name: Pull Azure Data
        run: |
          python sources/msft-azurecloud/azure_ips.py          

      - name: Pull Threatfox Data
        run: |
          python sources/threatfox-iocs/threatfox-ioc.py
          
      - name: Pull BinaryEdge Data
        run: |
          python sources/binaryedge/binaryedge.py          

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Automated Data update: $(date)" || echo "No iCloud Proxy changes to commit"
          git pull --rebase && git push

 
 