name: Generate iCloud Relay IP Ranges

on:
  schedule:
    - cron: '0 2 * * *' # lets run 2am utc daily
  workflow_dispatch: # Allows you to run this manually for testing

permissions:
  contents: write # to put the csv into repo

jobs:
  run-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run script
        run: |
          python sources/icloud-proxy/icloud-proxy.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/icloudegress/
          git commit -m "Automated iCloud Proxy Data update: $(date)" || echo "No iCloud Proxy changes to commit"
          git push
